AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot Lambda - CustomerManagerService

Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64

Resources:
  CustomerServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.quickconnect.customerManagerService.lambda.StreamLambdaHandler
      Runtime: java17
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:us-east-2:621553445876:table/Customers